const Quiz = [
  {
    title: "က", //used as main title in homescreen
    id: 1, //just main id

    data: [
      //used as each lesson data
      {
        id: 1, //lesson id
        name: "၁", //lesson number for view in homescreen
        sub: "၁", //lesson sub title
        type: "Tracing", //lesson type
        data: require("../assets/lesson_gif/1.ka_gyi.gif"), //used to construct UI and question data
        question: "", //used as question to view
        answer: "", //used  to check answer
        anim: require("../assets/Animal/cat.json"), // users as lesson animation in homescreen
        sound: require("../assets/Music/sound/1.ka.mp3"),
      },
      {
        id: 2,
        name: "၁",
        sub: "၂",
        type: "Train",
        data: ["က", "တ", "ဃ", "ထ", "က", "ယ", "တ", "ယ", "က", "ယ", "သ", "က"],
        question: "က",
        answer: "က",
        anim: require("../assets/Animal/baby.json"),
        sound: require("../assets/Music/sound/1.ka.mp3"),
      },
      {
        id: 3,
        name: "၁",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/baby.json"),
            title: "ကလေး",
            id: "က",
          },
          {
            anim: require("../assets/Animal/dog.json"),
            title: "ခွေး",
            id: "ခ",
          },
        ],
        question: "က",
        answer: "က",
        anim: require("../assets/Animal/dance.json"),
        sound: require("../assets/Music/sound/1.ka.mp3"),
      },
      {
        id: 4,
        name: "၁",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "က", img: require("../assets/dropItems/star.png") },
          { id: "တ", img: require("../assets/dropItems/moon.png") },
          { id: "ယ", img: require("../assets/dropItems/sunny.png") },
          { id: "သ", img: require("../assets/dropItems/cloud.png") },
        ],
        question: "က",
        answer: "က",
        anim: require("../assets/Animal/crab.json"),
        sound: require("../assets/Music/sound/1.ka.mp3"),
      },
    ],
  },
  {
    title: "ခ",
    id: 2,
    data: [
      {
        id: 1,
        name: "၂",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/2.kha_kway.gif"),
        question: "ခ",
        answer: "ခ",
        anim: require("../assets/Animal/dog.json"),
      },
      {
        id: 2,
        name: "၂",
        sub: "၂",
        type: "Train",
        data: ["ခ", "ဆ", "စ", "စ", "ေ", "ခ", "င", "ခ", "၁", "ဆ", "ပ", "ခ"],
        question: "ခ",
        answer: "ခ",
        anim: require("../assets/Animal/fork.json"),
      },
      {
        id: 3,
        name: "၂",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/guitar.json"),
            title: "ကလေး",
            id: "က",
          },
          {
            anim: require("../assets/Animal/dog.json"),
            title: "ခွေး",
            id: "ခ",
          },
        ],
        question: "ခ",
        answer: "ခ",
        anim: require("../assets/Animal/dance.json"),
      },
      {
        id: 4,
        name: "၂",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "စ", img: require("../assets/dropItems/star.png") },
          { id: "ခ", img: require("../assets/dropItems/moon.png") },
          { id: "ဂ", img: require("../assets/dropItems/sunny.png") },
          { id: "ပ", img: require("../assets/dropItems/cloud.png") },
        ],
        question: "ခ",
        answer: "ခ",
        anim: require("../assets/Animal/book.json"),
        sound: require("../assets/Music/sound/2.kha.mp3"),
      },
    ],
  },
  {
    title: "ဂ",
    id: 3,
    data: [
      {
        id: 1,
        name: "၃",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/3.ga_ngal.gif"),
        question: "ဂ",
        answer: "ဂ",
        anim: require("../assets/Animal/guitar.json"),
      },
      {
        id: 2,
        name: "၃",
        sub: "၂",
        type: "Train",
        data: ["ဂ", "ပ", "င", "င", "ပ", "ဂ", "က", "ဂ", "၁", "ဂ", "ယ", "ခ"],
        question: "ဂ",
        answer: "ဂ",
        anim: require("../assets/Animal/crab.json"),
      },
      {
        id: 3,
        name: "၃",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/crab.json"),
            title: "ကလေး",
            id: "ဂ",
          },
          {
            anim: require("../assets/Animal/dog.json"),
            title: "ခွေး",
            id: "ခ",
          },
        ],
        question: "ဂ",
        answer: "ဂ",
        anim: require("../assets/Animal/golf.json"),
      },
      {
        id: 4,
        name: "၃",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "ပ", img: require("../assets/dropItems/star.png") },
          { id: "ဝ", img: require("../assets/dropItems/moon.png") },
          { id: "ဂ", img: require("../assets/dropItems/sunny.png") },
          { id: "င", img: require("../assets/dropItems/cloud.png") },
        ],
        question: "ဂ",
        answer: "ဂ",
        anim: require("../assets/Animal/dog.json"),
        sound: require("../assets/Music/sound/3.ga_ngal.mp3"),
      },
    ],
  },
  {
    title: "င",
    data: [
      {
        id: 1,
        name: "၄",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/4.nga.gif"),
        question: "င",
        answer: "င",
        anim: require("../assets/Animal/owl.json"),
      },
      {
        id: 2,
        name: "၄",
        sub: "၂",
        type: "Train",
        data: ["ဂ", "ပ", "င", "င", "၁", "ပ", "ပ", "ဝ", "င", "၁", "ယ", "င"],
        question: "င",
        answer: "င",
        anim: require("../assets/Animal/book.json"),
      },
      {
        id: 3,
        name: "၄",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/baby.json"),
            title: "ကလေး",
            id: "က",
          },
          {
            anim: require("../assets/Animal/chili.json"),
            title: "ငရုတ်သီး",
            id: "င",
          },
        ],
        question: "င",
        answer: "င",
        anim: require("../assets/Animal/dance.json"),
      },
      {
        id: 4,
        name: "၄",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "ပ", img: require("../assets/dropItems/star.png") },
          { id: "မ", img: require("../assets/dropItems/moon.png") },
          { id: "ဂ", img: require("../assets/dropItems/sunny.png") },
          { id: "င", img: require("../assets/dropItems/cloud.png") },
        ],
        question: "င",
        answer: "င",
        anim: require("../assets/Animal/book.json"),
        sound: require("../assets/Music/sound/2.kha.mp3"),
      },
    ],
  },
  {
    title: "*",
    data: [
      {
        id: 1,
        name: "****",
        sub: "၁",
        type: "Revision",
        data: {
          leftData: ["ည", "ဆ", "စ", "ဇ"],
          rightData: ["စ", "ည", "ဇ", "ဆ"],
        },
        anim: require("../assets/Animal/owl.json"),
      },
    ],
  },
  {
    title: "စ",
    data: [
      {
        id: 1,
        name: "၅",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/5.sa_lone.gif"),
        question: "စ",
        answer: "စ",
        anim: require("../assets/Animal/chili.json"),
      },
      {
        id: 2,
        name: "၅",
        sub: "၂",
        type: "Train",
        data: ["စ", "ဓ", "ဇ", "ခ", "ဓ", "စ", "ပ", "စ", "ဇ", "ဆ", "ပ", "စ"],
        question: "စ",
        answer: "စ",
        anim: require("../assets/Animal/book.json"),
      },
      {
        id: 3,
        name: "၅",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/book.json"),
            title: "စာအုပ်",
            id: "စ",
          },
          {
            anim: require("../assets/Animal/cloud.json"),
            title: "တိမ်",
            id: "တ",
          },
        ],
        question: "စ",
        answer: "စ",
        anim: require("../assets/Animal/dance.json"),
      },
      {
        id: 4,
        name: "၅",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "မ", img: require("../assets/dropItems/star.png") },
          { id: "စ", img: require("../assets/dropItems/moon.png") },
          { id: "ခ", img: require("../assets/dropItems/sunny.png") },
          { id: "ဖ", img: require("../assets/dropItems/cloud.png") },
        ],
        question: "စ",
        answer: "စ",
        anim: require("../assets/Animal/owl.json"),
        sound: require("../assets/Music/sound/2.kha.mp3"),
      },
    ],
  },
  {
    title: "ဆ",
    data: [
      {
        id: 1,
        name: "၆",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/6.sa_lain.gif"),
        question: "ဆ",
        answer: "ဆ",
        anim: require("../assets/Animal/cat.json"),
      },
      {
        id: 2,
        name: "၆",
        sub: "၂",
        type: "Train",
        data: ["ဆ", "ခ", "သ", "သ", "ဆ", "ဇ", "ခ", "ထ", "ဆ", "ယ", "ဆ", "သ"],
        question: "ဆ",
        answer: "ဆ",
        anim: require("../assets/Animal/dog.json"),
      },
      {
        id: 3,
        name: "၆",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/book.json"),
            title: "စာအုပ်",
            id: "စ",
          },
          {
            anim: require("../assets/Animal/teacher.json"),
            title: "ဆရာမ",
            id: "ဆ",
          },
        ],
        question: "ဆ",
        answer: "ဆ",
        anim: require("../assets/Animal/crab.json"),
      },
      {
        id: 4,
        name: "၆",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "သ", img: require("../assets/dropItems/star.png") },
          { id: "ထ", img: require("../assets/dropItems/moon.png") },
          { id: "တ", img: require("../assets/dropItems/sunny.png") },
          { id: "ဆ", img: require("../assets/dropItems/cloud.png") },
        ],
        question: "ဆ",
        answer: "ဆ",
        anim: require("../assets/Animal/teacher.json"),
        sound: require("../assets/Music/sound/2.kha.mp3"),
      },
    ],
  },
  {
    title: "ဇ",
    data: [
      {
        id: 1,
        name: "၇",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/7.za_kwal.gif"),
        question: "ဇ",
        answer: "ဇ",
        anim: require("../assets/Animal/cloud.json"),
      },
      {
        id: 2,
        name: "၇",
        sub: "၂",
        type: "Train",
        data: ["ဆ", "ခ", "သ", "သ", "ဆ", "ဇ", "ခ", "ထ", "ဆ", "ယ", "ဆ", "သ"],
        question: "ဇ",
        answer: "ဇ",
        anim: require("../assets/Animal/book.json"),
      },
      {
        id: 3,
        name: "၇",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/owl.json"),
            title: "ဇီးကွက်",
            id: "ဇ",
          },
          {
            anim: require("../assets/Animal/dog.json"),
            title: "ခွေး",
            id: "ခ",
          },
        ],
        question: "ဇ",
        answer: "ဇ",
        anim: require("../assets/Animal/guitar.json"),
      },
      {
        id: 4,
        name: "၇",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "ဓ", img: require("../assets/dropItems/star.png") },
          { id: "မ", img: require("../assets/dropItems/moon.png") },
          { id: "ဇ", img: require("../assets/dropItems/sunny.png") },
          { id: "ခ", img: require("../assets/dropItems/cloud.png") },
        ],
        question: "ဇ",
        answer: "ဇ",
        anim: require("../assets/Animal/owl.json"),
        sound: require("../assets/Music/sound/8.za_kwal.mp3"),
      },
    ],
  },
  {
    title: "ည",
    data: [
      {
        id: 1,
        name: "၈",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/8.nya.gif"),
        question: "ည",
        answer: "ည",
        anim: require("../assets/Animal/book.json"),
      },
      {
        id: 2,
        name: "၈",
        sub: "၂",
        type: "Train",
        data: ["ည", "ယ", "ထ", "ဘ", "ည", "သ", "တ", "ထ", "ည", "သ", "ယ", "ည"],
        question: "ည",
        answer: "ည",
        anim: require("../assets/Animal/dance.json"),
      },
      {
        id: 3,
        name: "၈",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/guitar.json"),
            title: "ဂစ်တာ",
            id: "ဂ",
          },
          {
            anim: require("../assets/Animal/evening.json"),
            title: "ညနေ",
            id: "ည",
          },
        ],
        question: "ည",
        answer: "ည",
        anim: require("../assets/Animal/owl.json"),
      },
      {
        id: 4,
        name: "၈",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "ဘ", img: require("../assets/dropItems/star.png") },
          { id: "သ", img: require("../assets/dropItems/moon.png") },
          { id: "ည", img: require("../assets/dropItems/sunny.png") },
          { id: "ဆ", img: require("../assets/dropItems/cloud.png") },
        ],
        question: "ည",
        answer: "ည",
        anim: require("../assets/Animal/evening.json"),
        sound: require("../assets/Music/sound/5.nya.mp3"),
      },
    ],
  },
  {
    title: "တ",
    data: [
      {
        id: 1,
        name: "၉",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/9.ta_win_pu.gif"),
        question: "တ",
        answer: "တ",
        anim: require("../assets/Animal/cloud.json"),
      },
      {
        id: 2,
        name: "၉",
        sub: "၂",
        type: "Train",
        data: ["တ", "ထ", "က", "သ", "ဆ", "တ", "ထ", "တ", "က", "သ", "ဘ", "တ"],
        question: "တ",
        answer: "တ",
        anim: require("../assets/Animal/knife.json"),
      },
      {
        id: 3,
        name: "၉",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/cloud.json"),
            title: "တိမ်",
            id: "တ",
          },
          {
            anim: require("../assets/Animal/knife.json"),
            title: "ဓား",
            id: "ဓ",
          },
        ],
        question: "တ",
        answer: "တ",
        anim: require("../assets/Animal/owl.json"),
      },
      {
        id: 4,
        name: "၉",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "တ", img: require("../assets/dropItems/star.png") },
          { id: "သ", img: require("../assets/dropItems/moon.png") },
          { id: "ဘ", img: require("../assets/dropItems/sunny.png") },
          { id: "က", img: require("../assets/dropItems/cloud.png") },
        ],
        question: "တ",
        answer: "တ",
        anim: require("../assets/Animal/evening.json"),
        sound: require("../assets/Music/sound/10.ta_win_pu.mp3"),
      },
    ],
  },
  {
    title: "ထ",
    data: [
      {
        id: 1,
        name: "၁၀",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/10.hta_sin_htoo.gif"),
        question: "ထ",
        answer: "ထ",
        anim: require("../assets/Animal/sun.json"),
      },
      {
        id: 2,
        name: "၁၀",
        sub: "၂",
        type: "Train",
        data: ["ထ", "တ", "က", "သ", "ထ", "တ", "ဘ", "တ", "ထ", "တ", "ထ", "ဘ"],
        question: "ထ",
        answer: "ထ",
        anim: require("../assets/Animal/flower.json"),
      },
      {
        id: 3,
        name: "၁၀",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/chair.json"),
            title: "ထိုင်ခုံ",
            id: "ထ",
          },
          {
            anim: require("../assets/Animal/cloud.json"),
            title: "တိမ်",
            id: "တ",
          },
        ],
        question: "ထ",
        answer: "ထ",
        anim: require("../assets/Animal/chair.json"),
      },
      {
        id: 4,
        name: "၁၀",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "တ", img: require("../assets/dropItems/star.png") },
          { id: "ထ", img: require("../assets/dropItems/moon.png") },
          { id: "က", img: require("../assets/dropItems/sunny.png") },
          { id: "ယ", img: require("../assets/dropItems/weather.png") },
        ],
        question: "ထ",
        answer: "ထ",
        anim: require("../assets/Animal/cloud.json"),
        sound: require("../assets/Music/sound/11.hta_sin_htoo.mp3"),
      },
    ],
  },
  {
    title: "ဒ",
    data: [
      {
        id: 1,
        name: "၁၁",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/11.da_dway.gif"),
        question: "ဒ",
        answer: "ဒ",
        anim: require("../assets/Animal/pig.json"),
      },
      {
        id: 2,
        name: "၁၁",
        sub: "၂",
        type: "Train",
        data: ["ဒ", "အ", "င", "စ", "ဒ", "ေ", "ဇ", "ထ", "ဒ", "ဓ", "ဒ", "ဆ"],
        question: "ဒ",
        answer: "ဒ",
        anim: require("../assets/Animal/moon.json"),
      },
      {
        id: 3,
        name: "၁၁",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/deer.json"),
            title: "ဒရယ်",
            id: "ဒ",
          },
          {
            anim: require("../assets/Animal/chair.json"),
            title: "ထိုင်ခုံ",
            id: "ထ",
          },
        ],
        question: "ဒ",
        answer: "ဒ",
        anim: require("../assets/Animal/deer.json"),
      },
      {
        id: 4,
        name: "၁၁",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "ဓ", img: require("../assets/dropItems/star.png") },
          { id: "ဒ", img: require("../assets/dropItems/moon.png") },
          { id: "အ", img: require("../assets/dropItems/sunny.png") },
          { id: "ဖ", img: require("../assets/dropItems/weather.png") },
        ],
        question: "ဒ",
        answer: "ဒ",
        anim: require("../assets/Animal/girl.json"),
        sound: require("../assets/Music/sound/12.da_dway.mp3"),
      },
    ],
  },
  {
    title: "ဓ",
    data: [
      {
        id: 1,
        name: "၁၂",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/12.da_out_chite.gif"),
        question: "ဓ",
        answer: "ဓ",
        anim: require("../assets/Animal/mango.json"),
      },
      {
        id: 2,
        name: "၁၂",
        sub: "၂",
        type: "Train",
        data: ["ဓ", "စ", "မ", "ဇ", "ဓ", "မ", "စ", "ထ", "ဓ", "သ", "ဓ", "မ"],
        question: "ဓ",
        answer: "ဓ",
        anim: require("../assets/Animal/knife.json"),
      },
      {
        id: 3,
        name: "၁၂",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/deer.json"),
            title: "ဒရယ်",
            id: "ဒ",
          },
          {
            anim: require("../assets/Animal/knife.json"),
            title: "ဓ",
            id: "ဓ",
          },
        ],
        question: "ဓ",
        answer: "ဓ",
        anim: require("../assets/Animal/teacher.json"),
      },
      {
        id: 4,
        name: "၁၂",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "စ", img: require("../assets/dropItems/star.png") },
          { id: "မ", img: require("../assets/dropItems/moon.png") },
          { id: "ဓ", img: require("../assets/dropItems/sunny.png") },
          { id: "ခ", img: require("../assets/dropItems/weather.png") },
        ],
        question: "ဓ",
        answer: "ဓ",
        anim: require("../assets/Animal/doll.json"),
        sound: require("../assets/Music/sound/13.da_out_chite.mp3"),
      },
    ],
  },
  {
    title: "န",
    data: [
      {
        id: 1,
        name: "၁၃",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/13.na_ngal.gif"),
        question: "န",
        answer: "န",
        anim: require("../assets/Animal/sun.json"),
      },
      {
        id: 2,
        name: "၁၃",
        sub: "၂",
        type: "Train",
        data: ["န", "မ", "အ", "ဘ", "ယ", "စျ", "ရ", "န", "ည", "မ", "အ", "န"],
        question: "န",
        answer: "န",
        anim: require("../assets/Animal/book.json"),
      },
      {
        id: 3,
        name: "၁၃",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/sun.json"),
            title: "နေ",
            id: "န",
          },
          {
            anim: require("../assets/Animal/ruler.json"),
            title: "ပေတံ",
            id: "ပ",
          },
        ],
        question: "န",
        answer: "န",
        anim: require("../assets/Animal/dance.json"),
      },
      {
        id: 4,
        name: "၁၃",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "ရ", img: require("../assets/dropItems/star.png") },
          { id: "န", img: require("../assets/dropItems/moon.png") },
          { id: "စ", img: require("../assets/dropItems/sunny.png") },
          { id: "က", img: require("../assets/dropItems/weather.png") },
        ],
        question: "န",
        answer: "န",
        anim: require("../assets/Animal/flower.json"),
        sound: require("../assets/Music/sound/14.na_ngal.mp3"),
      },
    ],
  },
  {
    title: "ပ",
    data: [
      {
        id: 1,
        name: "၁၄",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/14.pa_sout.gif"),
        question: "ပ",
        answer: "ပ",
        anim: require("../assets/Animal/ruler.json"),
      },
      {
        id: 2,
        name: "၁၄",
        sub: "၂",
        type: "Train",
        data: ["ပ", "ဝ", "က", "မ", "သ", "ပ", "ဆ", "မ", "ပ", "ဖ", "ပ", "ည"],
        question: "ပ",
        answer: "ပ",
        anim: require("../assets/Animal/rabbit.json"),
      },
      {
        id: 3,
        name: "၁၄",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/watermelon.json"),
            title: "ဖရဲသီး",
            id: "ဖ",
          },
          {
            anim: require("../assets/Animal/ruler.json"),
            title: "ပေတံ",
            id: "ပ",
          },
        ],
        question: "ပ",
        answer: "ပ",
        anim: require("../assets/Animal/wheel.json"),
      },
      {
        id: 4,
        name: "၁၄",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "ပ", img: require("../assets/dropItems/star.png") },
          { id: "မ", img: require("../assets/dropItems/moon.png") },
          { id: "ဖ", img: require("../assets/dropItems/sunny.png") },
          { id: "င", img: require("../assets/dropItems/weather.png") },
        ],
        question: "ပ",
        answer: "ပ",
        anim: require("../assets/Animal/train.json"),
        sound: require("../assets/Music/sound/15.pa_sout.mp3"),
      },
    ],
  },
  {
    title: "ဖ",
    data: [
      {
        id: 1,
        name: "၁၄",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/15.pha_oo_htote.gif"),
        question: "ဖ",
        answer: "ဖ",
        anim: require("../assets/Animal/watermelon.json"),
      },
      {
        id: 2,
        name: "၁၅",
        sub: "၂",
        type: "Train",
        data: ["ဖ", "ပ", "ဝ", "မ", "ဖ", "ပ", "ဝ", "မ", "ဖ", "ခ", "မ", "ဖ"],
        question: "ဖ",
        answer: "ဖ",
        anim: require("../assets/Animal/drum.json"),
      },
      {
        id: 3,
        name: "၁၅",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/watermelon.json"),
            title: "ဖရဲသီး",
            id: "ဖ",
          },
          {
            anim: require("../assets/Animal/flower.json"),
            title: "ပန်း",
            id: "ပ",
          },
        ],
        question: "ဖ",
        answer: "ဖ",
        anim: require("../assets/Animal/moon.json"),
      },
      {
        id: 4,
        name: "၁၅",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "စ", img: require("../assets/dropItems/star.png") },
          { id: "မ", img: require("../assets/dropItems/moon.png") },
          { id: "ဖ", img: require("../assets/dropItems/sunny.png") },
          { id: "ပ", img: require("../assets/dropItems/weather.png") },
        ],
        question: "ဖ",
        answer: "ဖ",
        anim: require("../assets/Animal/owl.json"),
        sound: require("../assets/Music/sound/16.pha_oo_htote.mp3"),
      },
    ],
  },
  {
    title: "ဗ",
    data: [
      {
        id: 1,
        name: "၁၆",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/16.ba_htet_chite.gif"),
        question: "ဗ",
        answer: "ဗ",
        anim: require("../assets/Animal/sun.json"),
      },
      {
        id: 2,
        name: "၁၆",
        sub: "၂",
        type: "Train",
        data: ["ဗ", "ဖ", "ပ", "မ", "ဖ", "ဗ", "ဇ", "ဖ", "ဗ", "မ", "ဗ", "ဖ"],
        question: "ဗ",
        answer: "ဗ",
        anim: require("../assets/Animal/baby.json"),
      },
      {
        id: 3,
        name: "၁၆",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/knife.json"),
            title: "ဓား",
            id: "ဓ",
          },
          {
            anim: require("../assets/Animal/drum.json"),
            title: "ဗုံ",
            id: "ဗ",
          },
        ],
        question: "ဗ",
        answer: "ဗ",
        anim: require("../assets/Animal/book.json"),
      },
      {
        id: 4,
        name: "၁၆",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "ဗ", img: require("../assets/dropItems/star.png") },
          { id: "မ", img: require("../assets/dropItems/moon.png") },
          { id: "ဖ", img: require("../assets/dropItems/sunny.png") },
          { id: "ခ", img: require("../assets/dropItems/weather.png") },
        ],
        question: "ဗ",
        answer: "ဗ",
        anim: require("../assets/Animal/drum.json"),
        sound: require("../assets/Music/sound/16.pha_oo_htote.mp3"),
      },
    ],
  },
  {
    title: "ဘ",
    data: [
      {
        id: 1,
        name: "၁၇",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/17.ba_gone.gif"),
        question: "ဘ",
        answer: "ဘ",
        anim: require("../assets/Animal/cloud.json"),
      },
      {
        id: 2,
        name: "၁၇",
        sub: "၂",
        type: "Train",
        data: ["ဘ", "ယ", "ထ", "ဘ", "ည", "သ", "တ", "ထ", "ဘ", "လ", "ဘ", "ယ"],
        question: "ဘ",
        answer: "ဘ",
        anim: require("../assets/Animal/moon.json"),
      },
      {
        id: 3,
        name: "၁၇",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/knife.json"),
            title: "ဓား",
            id: "ဓ",
          },
          {
            anim: require("../assets/Animal/wheel.json"),
            title: "ဘီး",
            id: "ဘ",
          },
        ],
        question: "ဘ",
        answer: "ဘ",
        anim: require("../assets/Animal/wheel.json"),
      },
      {
        id: 4,
        name: "၁၇",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "ဘ", img: require("../assets/dropItems/star.png") },
          { id: "လ", img: require("../assets/dropItems/moon.png") },
          { id: "သ", img: require("../assets/dropItems/sunny.png") },
          { id: "ဟ", img: require("../assets/dropItems/weather.png") },
        ],
        question: "ဘ",
        answer: "ဘ",
        anim: require("../assets/Animal/crab.json"),
        sound: require("../assets/Music/sound/16.pha_oo_htote.mp3"),
      },
    ],
  },
  {
    title: "မ",
    data: [
      {
        id: 1,
        name: "၁၈",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/18.ma.gif"),
        question: "မ",
        answer: "မ",
        anim: require("../assets/Animal/flower.json"),
      },
      {
        id: 2,
        name: "၁၈",
        sub: "၂",
        type: "Train",
        data: ["ပ", "င", "မ", "စ", "ဆ", "မ", "ဖ", "ဗ", "မ", "သ", "မ", "ည"],
        question: "မ",
        answer: "မ",
        anim: require("../assets/Animal/girl.json"),
      },
      {
        id: 3,
        name: "၁၈",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/girl.json"),
            title: "မမ",
            id: "မ",
          },
          {
            anim: require("../assets/Animal/wheel.json"),
            title: "ဘီး",
            id: "ဘ",
          },
        ],
        question: "မ",
        answer: "မ",
        anim: require("../assets/Animal/guitar.json"),
      },
      {
        id: 4,
        name: "၁၈",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "ခ", img: require("../assets/dropItems/star.png") },
          { id: "ဖ", img: require("../assets/dropItems/moon.png") },
          { id: "မ", img: require("../assets/dropItems/sunny.png") },
          { id: "စ", img: require("../assets/dropItems/weather.png") },
        ],
        question: "မ",
        answer: "မ",
        anim: require("../assets/Animal/evening.json"),
        sound: require("../assets/Music/sound/16.pha_oo_htote.mp3"),
      },
    ],
  },
  {
    title: "ယ",
    data: [
      {
        id: 1,
        name: "၁၉",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/19.ya_pa_lat.gif"),
        question: "ယ",
        answer: "ယ",
        anim: require("../assets/Animal/rabbit.json"),
      },
      {
        id: 2,
        name: "၁၉",
        sub: "၂",
        type: "Train",
        data: ["ယ", "တ", "ထ", "ဘ", "ယ", "သ", "တ", "ထ", "ယ", "ဟ", "ယ", "ဘ"],
        question: "ယ",
        answer: "ယ",
        anim: require("../assets/Animal/cat.json"),
      },
      {
        id: 3,
        name: "၁၉",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/guitar.json"),
            title: "ဂစ်တာ",
            id: "ဂ",
          },
          {
            anim: require("../assets/Animal/rabbit.json"),
            title: "ယူန်",
            id: "ယ",
          },
        ],
        question: "ယ",
        answer: "ယ",
        anim: require("../assets/Animal/owl.json"),
      },
      {
        id: 4,
        name: "၁၉",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "က", img: require("../assets/dropItems/star.png") },
          { id: "သ", img: require("../assets/dropItems/moon.png") },
          { id: "လ", img: require("../assets/dropItems/sunny.png") },
          { id: "ယ", img: require("../assets/dropItems/weather.png") },
        ],
        question: "ယ",
        answer: "ယ",
        anim: require("../assets/Animal/pig.json"),
        sound: require("../assets/Music/sound/16.pha_oo_htote.mp3"),
      },
    ],
  },
  {
    title: "ရ",
    data: [
      {
        id: 1,
        name: "၂၀",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/20.ra_gout.gif"),
        question: "ရ",
        answer: "ရ",
        anim: require("../assets/Animal/mango.json"),
      },
      {
        id: 2,
        name: "၂၀",
        sub: "၂",
        type: "Train",
        data: ["ရ", "ယ", "ထ", "န", "အ", "ရ", "စျ", "ရ", "ည", "ယ", "ည", "ရ"],
        question: "ရ",
        answer: "ရ",
        anim: require("../assets/Animal/chicken.json"),
      },
      {
        id: 3,
        name: "၂၀",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/girl.json"),
            title: "မမ",
            id: "မ",
          },
          {
            anim: require("../assets/Animal/train.json"),
            title: "ရထား",
            id: "ရ",
          },
        ],
        question: "ရ",
        answer: "ရ",
        anim: require("../assets/Animal/train.json"),
      },
      {
        id: 4,
        name: "၂၀",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "ရ", img: require("../assets/dropItems/star.png") },
          { id: "န", img: require("../assets/dropItems/moon.png") },
          { id: "ဒ", img: require("../assets/dropItems/sunny.png") },
          { id: "စ", img: require("../assets/dropItems/weather.png") },
        ],
        question: "ရ",
        answer: "ရ",
        anim: require("../assets/Animal/curry.json"),
        sound: require("../assets/Music/sound/16.pha_oo_htote.mp3"),
      },
    ],
  },
  {
    title: "လ",
    data: [
      {
        id: 1,
        name: "၂၁",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/21.la.gif"),
        question: "လ",
        answer: "လ",
        anim: require("../assets/Animal/dance.json"),
      },
      {
        id: 2,
        name: "၂၁",
        sub: "၂",
        type: "Train",
        data: ["လ", "ယ", "ထ", "ဘ", "လ", "သ", "တ", "ထ", "လ", "သ", "ထ", "လ"],
        question: "လ",
        answer: "လ",
        anim: require("../assets/Animal/moon.json"),
      },
      {
        id: 3,
        name: "၂၁",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/moon.json"),
            title: "လ",
            id: "လ",
          },
          {
            anim: require("../assets/Animal/train.json"),
            title: "ရထား",
            id: "ရ",
          },
        ],
        question: "လ",
        answer: "လ",
        anim: require("../assets/Animal/deer.json"),
      },
      {
        id: 4,
        name: "၂၁",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "ယ", img: require("../assets/dropItems/star.png") },
          { id: "က", img: require("../assets/dropItems/moon.png") },
          { id: "သ", img: require("../assets/dropItems/sunny.png") },
          { id: "လ", img: require("../assets/dropItems/weather.png") },
        ],
        question: "လ",
        answer: "လ",
        anim: require("../assets/Animal/teacher.json"),
        sound: require("../assets/Music/sound/16.pha_oo_htote.mp3"),
      },
    ],
  },
  {
    title: "ဝ",
    data: [
      {
        id: 1,
        name: "၂၂",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/22.wa.gif"),
        question: "ဝ",
        answer: "ဝ",
        anim: require("../assets/Animal/sun.json"),
      },
      {
        id: 2,
        name: "၂၂",
        sub: "၂",
        type: "Train",
        data: ["ဝ", "ယ", "ထ", "ပ", "ဖ", "ဝ", "ဂ", "ဇ", "ဝ", "ပ", "ထ", "ဝ"],
        question: "ဝ",
        answer: "ဝ",
        anim: require("../assets/Animal/pig.json"),
      },
      {
        id: 3,
        name: "၂၂",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/rabbit.json"),
            title: "ယုန်",
            id: "ယ",
          },
          {
            anim: require("../assets/Animal/pig.json"),
            title: "ဝက်",
            id: "ဝ",
          },
        ],
        question: "ဝ",
        answer: "ဝ",
        anim: require("../assets/Animal/chili.json"),
      },
      {
        id: 4,
        name: "၂၂",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "ဝ", img: require("../assets/dropItems/star.png") },
          { id: "ပ", img: require("../assets/dropItems/moon.png") },
          { id: "င", img: require("../assets/dropItems/sunny.png") },
          { id: "ဂ", img: require("../assets/dropItems/weather.png") },
        ],
        question: "ဝ",
        answer: "ဝ",
        anim: require("../assets/Animal/dog.json"),
        sound: require("../assets/Music/sound/16.pha_oo_htote.mp3"),
      },
    ],
  },
  {
    title: "သ",
    data: [
      {
        id: 1,
        name: "၂၃",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/23.tha.gif"),
        question: "သ",
        answer: "သ",
        anim: require("../assets/Animal/doll.json"),
      },
      {
        id: 2,
        name: "၂၃",
        sub: "၂",
        type: "Train",
        data: ["သ", "ယ", "ထ", "ဘ", "ည", "သ", "တ", "ထ", "သ", "သ", "ယ", "ဟ"],
        question: "သ",
        answer: "သ",
        anim: require("../assets/Animal/drum.json"),
      },
      {
        id: 3,
        name: "၂၃",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/mango.json"),
            title: "သရက်သီး",
            id: "သ",
          },
          {
            anim: require("../assets/Animal/watermelon.json"),
            title: "ဖရဲသီး",
            id: "ဖ",
          },
        ],
        question: "သ",
        answer: "သ",
        anim: require("../assets/Animal/mango.json"),
      },
      {
        id: 4,
        name: "၂၃",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "သ", img: require("../assets/dropItems/star.png") },
          { id: "က", img: require("../assets/dropItems/moon.png") },
          { id: "ယ", img: require("../assets/dropItems/sunny.png") },
          { id: "လ", img: require("../assets/dropItems/weather.png") },
        ],
        question: "သ",
        answer: "သ",
        anim: require("../assets/Animal/knife.json"),
        sound: require("../assets/Music/sound/16.pha_oo_htote.mp3"),
      },
    ],
  },
  {
    title: "ဟ",
    data: [
      {
        id: 1,
        name: "၂၄",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/24.ha.gif"),
        question: "ဟ",
        answer: "ဟ",
        anim: require("../assets/Animal/chili.json"),
      },
      {
        id: 2,
        name: "၂၄",
        sub: "၂",
        type: "Train",
        data: ["ဟ", "ယ", "ထ", "ဘ", "ဟ", "သ", "တ", "ထ", "ဟ", "သ", "ဟ", "တ"],
        question: "ဟ",
        answer: "ဟ",
        anim: require("../assets/Animal/mango.json"),
      },
      {
        id: 3,
        name: "၂၄",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/mango.json"),
            title: "သရက်သီး",
            id: "သ",
          },
          {
            anim: require("../assets/Animal/curry.json"),
            title: "ဟင်း",
            id: "ဟ",
          },
        ],
        question: "ဟ",
        answer: "ဟ",
        anim: require("../assets/Animal/book.json"),
      },
      {
        id: 4,
        name: "၂၄",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "ဟ", img: require("../assets/dropItems/star.png") },
          { id: "ဘ", img: require("../assets/dropItems/moon.png") },
          { id: "ယ", img: require("../assets/dropItems/sunny.png") },
          { id: "အ", img: require("../assets/dropItems/weather.png") },
        ],
        question: "ဟ",
        answer: "ဟ",
        anim: require("../assets/Animal/teacher.json"),
        sound: require("../assets/Music/sound/16.pha_oo_htote.mp3"),
      },
    ],
  },
  {
    title: "အ",
    data: [
      {
        id: 1,
        name: "၂၅",
        sub: "၁",
        type: "Tracing",
        data: require("../assets/lesson_gif/25.a.gif"),
        question: "အ",
        answer: "အ",
        anim: require("../assets/Animal/doll.json"),
      },
      {
        id: 2,
        name: "၂၅",
        sub: "၂",
        type: "Train",
        data: ["အ", "ယ", "ထ", "ဘ", "အ", "သ", "တ", "ထ", "အ", "သ", "အ", "ည"],
        question: "အ",
        answer: "အ",
        anim: require("../assets/Animal/deer.json"),
      },
      {
        id: 3,
        name: "၂၅",
        sub: "၃",
        type: "Matching",
        data: [
          {
            anim: require("../assets/Animal/doll.json"),
            title: "အရုပ်",
            id: "အ",
          },
          {
            anim: require("../assets/Animal/dog.json"),
            title: "ခွေး",
            id: "ခ",
          },
        ],
        question: "အ",
        answer: "အ",
        anim: require("../assets/Animal/owl.json"),
      },
      {
        id: 4,
        name: "၂၅",
        sub: "၄",
        type: "DnD",
        data: [
          { id: "ဘ", img: require("../assets/dropItems/star.png") },
          { id: "အ", img: require("../assets/dropItems/moon.png") },
          { id: "လ", img: require("../assets/dropItems/sunny.png") },
          { id: "က", img: require("../assets/dropItems/weather.png") },
        ],
        question: "အ",
        answer: "အ",
        anim: require("../assets/Animal/girl.json"),
        sound: require("../assets/Music/sound/16.pha_oo_htote.mp3"),
      },
    ],
  },
];

export { Quiz };
